[features]
resolution = true
skip-lint = false

[programs.localnet]
valkyrix_ledger = "Esj1LL1kQTYZ6kVi2wbiJiHbEs3cAiW6dDsZyjdZpmNo"

[programs.devnet]
valkyrix_ledger = "Esj1LL1kQTYZ6kVi2wbiJiHbEs3cAiW6dDsZyjdZpmNo"

[provider]
cluster = "Devnet"
wallet = "C:/Users/Kant/.config/solana/deploy-keypair.json"

[scripts]
test = "cargo test --manifest-path ./Cargo.toml -- --nocapture"
