[features]
resolution = true
skip-lint = false

[programs.localnet]
valkyrix_ledger = "NkxXENw6u1jWc8iUo28M9NiDVEcoUdqGiGZ3TyNf9Xn"

[programs.devnet]
valkyrix_ledger = "NkxXENw6u1jWc8iUo28M9NiDVEcoUdqGiGZ3TyNf9Xn"

[provider]
cluster = "Devnet"
wallet = "C:/Users/Kant/.config/solana/deploy-keypair.json"

[scripts]
test = "cargo test --manifest-path ./Cargo.toml -- --nocapture"
